"""update ocr_configs with api fields

Revision ID: c853a95e4e86
Revises: 0001
Create Date: 2026-06-19 12:22:52.157937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c853a95e4e86'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_configs', sa.Column('api_base_url', sa.String(length=500), nullable=True))
    op.add_column('ocr_configs', sa.Column('api_key', sa.Text(), nullable=True))
    op.drop_column('ocr_configs', 'use_gpu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_configs', sa.Column('use_gpu', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('ocr_configs', 'api_key')
    op.drop_column('ocr_configs', 'api_base_url')
    # ### end Alembic commands ###
